version: '3'

services:
    nextcloud:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${NEXTCLOUD_IMAGE}

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: ${NGINX_IMAGE}

    elasticsearch:
        build:
            context: ./docker/elasticsearch
            dockerfile: Dockerfile
        image: ${ELASTICSEARCH_IMAGE}
