version: '3'

services:
    nextcloud:
        build:
            context: .
            dockerfile: Dockerfile
        image: docker-hub.extalion.com/extalion/nextcloud

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: docker-hub.extalion.com/extalion/nextcloud_nginx

    elasticsearch:
        build:
            context: ./docker/elasticsearch
            dockerfile: Dockerfile
        image: docker-hub.extalion.com/extalion/nextcloud_elasticsearch
