version: '3'

services:
    nextcloud:
        image: docker-hub.extalion.com/extalion/nextcloud
        restart: always
        ports:
            - "127.0.0.1:8889:80"
        volumes:
            - ./nextcloud:/var/www/html
            - ./apps:/var/www/html/custom_apps
            - ./config:/var/www/html/config
            - ./data:/var/www/html/data
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
            - MYSQL_HOST=db
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
            - MYSQL_USER=${MYSQL_USER:-nextcloud}
            - REDIS_HOST=redis
            - REDIS_HOST_PASSWORD=redis_pass
            - "NEXTCLOUD_TRUSTED_DOMAINS=cloud.d0niek.pl office.d0niek.pl"
        depends_on:
            - db
            - redis

    db:
        image: mariadb:10.5
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - ./db:/var/lib/mysql
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is not set or empty}
            - MYSQL_USER=${MYSQL_USER:-nextcloud}

    redis:
        image: redis:alpine
        restart: always
        command: redis-server --requirepass redis_pass --maxmemory 1GB

    collabora:
        image: collabora/code
        environment:
            - "username=root"
            - "password=BIUgIT78G6rFF6FYVgfF"
            - "domain=cloud.d0niek.pl"
            - "server_name=office.d0niek.pl"
        restart: always
        ports:
            - "127.0.0.1:9980:9980"
        cap_add:
            - MKNOD
