version: '3'

services:
    nextcloud:
        image: docker-hub.extalion.com/extalion/nextcloud
        restart: always
        ports:
            - "127.0.0.1:${NEXTCLOUD_PORT:?NEXTCLOUD_PORT is not set or empty}:80"
        volumes:
            - ./apps:/var/www/html/custom_apps
            - ./config:/var/www/html/config
            - ./data:/var/www/html/data
            - ./nextcloud:/var/www/html
        depends_on:
            - db
            - redis
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
            - MYSQL_HOST=db
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
            - MYSQL_USER=${MYSQL_USER:-nextcloud}
            - REDIS_HOST=redis
            - REDIS_HOST_PASSWORD=redis_pass
            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.d0niek.pl office.d0niek.pl

    db:
        image: mariadb:10.5
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - ./db:/var/lib/mysql
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
            - MYSQL_RANDOM_ROOT_PASSWORD='1'
            - MYSQL_USER=${MYSQL_USER:-nextcloud}

    redis:
        image: redis:alpine
        restart: always
        command: redis-server --requirepass redis_pass --maxmemory 1GB

    collabora:
        image: collabora/code
        restart: always
        ports:
            - "127.0.0.1:${COLLABORA_PORT:?COLLABORA_PORT is not set or empty}:9980"
        environment:
            - username=root
            - password=BIUgIT78G6rFF6FYVgfF
            - domain=cloud.d0niek.pl
            - server_name=office.d0niek.pl
        cap_add:
            - MKNOD
